baseURL = "https://www.gopesh.tech"
languageCode = "en-us"
title = "Beyond the Byte"
paginate = 20

[params]
subtitle = "Building the Future, One Line of Code at a Time"
thumbnail = "thumb.jpg"

[taxonomies]
   tag = "tags"
   author = "authors"

[menu]
   [[menu.header]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

   [[menu.header]]
      identifier = "thoughts"
      name = "Thoughts"
      url = "/blog"
      weight = 2
